#!/bin/bash
SEL_COEFF=$1
DIFF_MEANS=$2

sed 's/rs1/rs1/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_1.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_1.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs2/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_2.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_2.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs3/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_3.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_3.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs4/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_4.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_4.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs5/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_5.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_5.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs6/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_6.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_6.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs7/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_7.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_7.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs8/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_8.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_8.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs9/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_9.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_9.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs10/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_10.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_10.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs11/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_11.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_11.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs12/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_12.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_12.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs13/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_13.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_13.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs14/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_14.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_14.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs15/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_15.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_15.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs16/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_16.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_16.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs17/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_17.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_17.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs18/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_18.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_18.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs19/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_19.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_19.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs20/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_20.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_20.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs21/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_21.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_21.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs22/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_22.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_22.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs23/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_23.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_23.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs24/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_24.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_24.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs25/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_25.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_25.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs26/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_26.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_26.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs27/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_27.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_27.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs28/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_28.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_28.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs29/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_29.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_29.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs30/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_30.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_30.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs31/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_31.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_31.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs32/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_32.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_32.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs33/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_33.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_33.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs34/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_34.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_34.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs35/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_35.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_35.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs36/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_36.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_36.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs37/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_37.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_37.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs38/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_38.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_38.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs39/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_39.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_39.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs40/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_40.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_40.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs41/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_41.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_41.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs42/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_42.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_42.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs43/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_43.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_43.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs44/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_44.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_44.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs45/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_45.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_45.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs46/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_46.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_46.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs47/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_47.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_47.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs48/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_48.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_48.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs49/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_49.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_49.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs50/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_50.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_50.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs51/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_51.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_51.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs52/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_52.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_52.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs53/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_53.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_53.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs54/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_54.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_54.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs55/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_55.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_55.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs56/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_56.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_56.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs57/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_57.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_57.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs58/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_58.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_58.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs59/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_59.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_59.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs60/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_60.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_60.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs61/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_61.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_61.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs62/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_62.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_62.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs63/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_63.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_63.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs64/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_64.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_64.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs65/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_65.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_65.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs66/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_66.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_66.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs67/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_67.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_67.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs68/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_68.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_68.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs69/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_69.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_69.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs70/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_70.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_70.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs71/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_71.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_71.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs72/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_72.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_72.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs73/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_73.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_73.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs74/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_74.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_74.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs75/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_75.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_75.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs76/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_76.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_76.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs77/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_77.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_77.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs78/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_78.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_78.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs79/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_79.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_79.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs80/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_80.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_80.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs81/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_81.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_81.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs82/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_82.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_82.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs83/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_83.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_83.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs84/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_84.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_84.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs85/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_85.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_85.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs86/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_86.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_86.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs87/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_87.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_87.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs88/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_88.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_88.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs89/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_89.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_89.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs90/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_90.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_90.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs91/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_91.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_91.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs92/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_92.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_92.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs93/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_93.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_93.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs94/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_94.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_94.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs95/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_95.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_95.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs96/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_96.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_96.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs97/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_97.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_97.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs98/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_98.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_98.assoc.linear.csv.filt.sumstats
sed 's/rs1/rs99/g' sel_${SEL_COEFF}_dm_${DIFF_MEANS}.i_99.assoc.linear.csv.filt.sumstats >  sel_${SEL_COEFF}_dm_${DIFF_MEANS}_toappend.i_99.assoc.linear.csv.filt.sumstats


sed 's/rs1/rs1/g' sel_${SEL_COEFF}.i_1.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_1.l2.ldscore 
sed 's/rs1/rs2/g' sel_${SEL_COEFF}.i_2.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_2.l2.ldscore 
sed 's/rs1/rs3/g' sel_${SEL_COEFF}.i_3.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_3.l2.ldscore 
sed 's/rs1/rs4/g' sel_${SEL_COEFF}.i_4.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_4.l2.ldscore 
sed 's/rs1/rs5/g' sel_${SEL_COEFF}.i_5.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_5.l2.ldscore 
sed 's/rs1/rs6/g' sel_${SEL_COEFF}.i_6.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_6.l2.ldscore 
sed 's/rs1/rs7/g' sel_${SEL_COEFF}.i_7.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_7.l2.ldscore 
sed 's/rs1/rs8/g' sel_${SEL_COEFF}.i_8.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_8.l2.ldscore 
sed 's/rs1/rs9/g' sel_${SEL_COEFF}.i_9.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_9.l2.ldscore 
sed 's/rs1/rs10/g' sel_${SEL_COEFF}.i_10.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_10.l2.ldscore 
sed 's/rs1/rs11/g' sel_${SEL_COEFF}.i_11.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_11.l2.ldscore 
sed 's/rs1/rs12/g' sel_${SEL_COEFF}.i_12.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_12.l2.ldscore 
sed 's/rs1/rs13/g' sel_${SEL_COEFF}.i_13.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_13.l2.ldscore 
sed 's/rs1/rs14/g' sel_${SEL_COEFF}.i_14.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_14.l2.ldscore 
sed 's/rs1/rs15/g' sel_${SEL_COEFF}.i_15.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_15.l2.ldscore 
sed 's/rs1/rs16/g' sel_${SEL_COEFF}.i_16.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_16.l2.ldscore 
sed 's/rs1/rs17/g' sel_${SEL_COEFF}.i_17.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_17.l2.ldscore 
sed 's/rs1/rs18/g' sel_${SEL_COEFF}.i_18.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_18.l2.ldscore 
sed 's/rs1/rs19/g' sel_${SEL_COEFF}.i_19.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_19.l2.ldscore 
sed 's/rs1/rs20/g' sel_${SEL_COEFF}.i_20.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_20.l2.ldscore 
sed 's/rs1/rs21/g' sel_${SEL_COEFF}.i_21.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_21.l2.ldscore 
sed 's/rs1/rs22/g' sel_${SEL_COEFF}.i_22.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_22.l2.ldscore 
sed 's/rs1/rs23/g' sel_${SEL_COEFF}.i_23.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_23.l2.ldscore 
sed 's/rs1/rs24/g' sel_${SEL_COEFF}.i_24.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_24.l2.ldscore 
sed 's/rs1/rs25/g' sel_${SEL_COEFF}.i_25.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_25.l2.ldscore 
sed 's/rs1/rs26/g' sel_${SEL_COEFF}.i_26.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_26.l2.ldscore 
sed 's/rs1/rs27/g' sel_${SEL_COEFF}.i_27.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_27.l2.ldscore 
sed 's/rs1/rs28/g' sel_${SEL_COEFF}.i_28.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_28.l2.ldscore 
sed 's/rs1/rs29/g' sel_${SEL_COEFF}.i_29.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_29.l2.ldscore 
sed 's/rs1/rs30/g' sel_${SEL_COEFF}.i_30.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_30.l2.ldscore 
sed 's/rs1/rs31/g' sel_${SEL_COEFF}.i_31.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_31.l2.ldscore 
sed 's/rs1/rs32/g' sel_${SEL_COEFF}.i_32.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_32.l2.ldscore 
sed 's/rs1/rs33/g' sel_${SEL_COEFF}.i_33.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_33.l2.ldscore 
sed 's/rs1/rs34/g' sel_${SEL_COEFF}.i_34.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_34.l2.ldscore 
sed 's/rs1/rs35/g' sel_${SEL_COEFF}.i_35.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_35.l2.ldscore 
sed 's/rs1/rs36/g' sel_${SEL_COEFF}.i_36.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_36.l2.ldscore 
sed 's/rs1/rs37/g' sel_${SEL_COEFF}.i_37.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_37.l2.ldscore 
sed 's/rs1/rs38/g' sel_${SEL_COEFF}.i_38.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_38.l2.ldscore 
sed 's/rs1/rs39/g' sel_${SEL_COEFF}.i_39.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_39.l2.ldscore 
sed 's/rs1/rs40/g' sel_${SEL_COEFF}.i_40.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_40.l2.ldscore 
sed 's/rs1/rs41/g' sel_${SEL_COEFF}.i_41.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_41.l2.ldscore 
sed 's/rs1/rs42/g' sel_${SEL_COEFF}.i_42.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_42.l2.ldscore 
sed 's/rs1/rs43/g' sel_${SEL_COEFF}.i_43.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_43.l2.ldscore 
sed 's/rs1/rs44/g' sel_${SEL_COEFF}.i_44.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_44.l2.ldscore 
sed 's/rs1/rs45/g' sel_${SEL_COEFF}.i_45.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_45.l2.ldscore 
sed 's/rs1/rs46/g' sel_${SEL_COEFF}.i_46.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_46.l2.ldscore 
sed 's/rs1/rs47/g' sel_${SEL_COEFF}.i_47.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_47.l2.ldscore 
sed 's/rs1/rs48/g' sel_${SEL_COEFF}.i_48.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_48.l2.ldscore 
sed 's/rs1/rs49/g' sel_${SEL_COEFF}.i_49.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_49.l2.ldscore 
sed 's/rs1/rs50/g' sel_${SEL_COEFF}.i_50.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_50.l2.ldscore 
sed 's/rs1/rs51/g' sel_${SEL_COEFF}.i_51.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_51.l2.ldscore 
sed 's/rs1/rs52/g' sel_${SEL_COEFF}.i_52.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_52.l2.ldscore 
sed 's/rs1/rs53/g' sel_${SEL_COEFF}.i_53.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_53.l2.ldscore 
sed 's/rs1/rs54/g' sel_${SEL_COEFF}.i_54.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_54.l2.ldscore 
sed 's/rs1/rs55/g' sel_${SEL_COEFF}.i_55.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_55.l2.ldscore 
sed 's/rs1/rs56/g' sel_${SEL_COEFF}.i_56.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_56.l2.ldscore 
sed 's/rs1/rs57/g' sel_${SEL_COEFF}.i_57.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_57.l2.ldscore 
sed 's/rs1/rs58/g' sel_${SEL_COEFF}.i_58.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_58.l2.ldscore 
sed 's/rs1/rs59/g' sel_${SEL_COEFF}.i_59.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_59.l2.ldscore 
sed 's/rs1/rs60/g' sel_${SEL_COEFF}.i_60.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_60.l2.ldscore 
sed 's/rs1/rs61/g' sel_${SEL_COEFF}.i_61.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_61.l2.ldscore 
sed 's/rs1/rs62/g' sel_${SEL_COEFF}.i_62.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_62.l2.ldscore 
sed 's/rs1/rs63/g' sel_${SEL_COEFF}.i_63.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_63.l2.ldscore 
sed 's/rs1/rs64/g' sel_${SEL_COEFF}.i_64.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_64.l2.ldscore 
sed 's/rs1/rs65/g' sel_${SEL_COEFF}.i_65.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_65.l2.ldscore 
sed 's/rs1/rs66/g' sel_${SEL_COEFF}.i_66.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_66.l2.ldscore 
sed 's/rs1/rs67/g' sel_${SEL_COEFF}.i_67.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_67.l2.ldscore 
sed 's/rs1/rs68/g' sel_${SEL_COEFF}.i_68.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_68.l2.ldscore 
sed 's/rs1/rs69/g' sel_${SEL_COEFF}.i_69.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_69.l2.ldscore 
sed 's/rs1/rs70/g' sel_${SEL_COEFF}.i_70.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_70.l2.ldscore 
sed 's/rs1/rs71/g' sel_${SEL_COEFF}.i_71.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_71.l2.ldscore 
sed 's/rs1/rs72/g' sel_${SEL_COEFF}.i_72.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_72.l2.ldscore 
sed 's/rs1/rs73/g' sel_${SEL_COEFF}.i_73.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_73.l2.ldscore 
sed 's/rs1/rs74/g' sel_${SEL_COEFF}.i_74.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_74.l2.ldscore 
sed 's/rs1/rs75/g' sel_${SEL_COEFF}.i_75.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_75.l2.ldscore 
sed 's/rs1/rs76/g' sel_${SEL_COEFF}.i_76.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_76.l2.ldscore 
sed 's/rs1/rs77/g' sel_${SEL_COEFF}.i_77.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_77.l2.ldscore 
sed 's/rs1/rs78/g' sel_${SEL_COEFF}.i_78.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_78.l2.ldscore 
sed 's/rs1/rs79/g' sel_${SEL_COEFF}.i_79.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_79.l2.ldscore 
sed 's/rs1/rs80/g' sel_${SEL_COEFF}.i_80.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_80.l2.ldscore 
sed 's/rs1/rs81/g' sel_${SEL_COEFF}.i_81.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_81.l2.ldscore 
sed 's/rs1/rs82/g' sel_${SEL_COEFF}.i_82.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_82.l2.ldscore 
sed 's/rs1/rs83/g' sel_${SEL_COEFF}.i_83.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_83.l2.ldscore 
sed 's/rs1/rs84/g' sel_${SEL_COEFF}.i_84.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_84.l2.ldscore 
sed 's/rs1/rs85/g' sel_${SEL_COEFF}.i_85.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_85.l2.ldscore 
sed 's/rs1/rs86/g' sel_${SEL_COEFF}.i_86.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_86.l2.ldscore 
sed 's/rs1/rs87/g' sel_${SEL_COEFF}.i_87.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_87.l2.ldscore 
sed 's/rs1/rs88/g' sel_${SEL_COEFF}.i_88.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_88.l2.ldscore 
sed 's/rs1/rs89/g' sel_${SEL_COEFF}.i_89.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_89.l2.ldscore 
sed 's/rs1/rs90/g' sel_${SEL_COEFF}.i_90.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_90.l2.ldscore 
sed 's/rs1/rs91/g' sel_${SEL_COEFF}.i_91.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_91.l2.ldscore 
sed 's/rs1/rs92/g' sel_${SEL_COEFF}.i_92.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_92.l2.ldscore 
sed 's/rs1/rs93/g' sel_${SEL_COEFF}.i_93.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_93.l2.ldscore 
sed 's/rs1/rs94/g' sel_${SEL_COEFF}.i_94.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_94.l2.ldscore 
sed 's/rs1/rs95/g' sel_${SEL_COEFF}.i_95.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_95.l2.ldscore 
sed 's/rs1/rs96/g' sel_${SEL_COEFF}.i_96.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_96.l2.ldscore 
sed 's/rs1/rs97/g' sel_${SEL_COEFF}.i_97.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_97.l2.ldscore 
sed 's/rs1/rs98/g' sel_${SEL_COEFF}.i_98.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_98.l2.ldscore 
sed 's/rs1/rs99/g' sel_${SEL_COEFF}.i_99.l2.ldscore  >  sel_${SEL_COEFF}_toappend.i_99.l2.ldscore 






 